(function(){
  'use strict';
    angular
        .module('angular')
        .factory('Countries', Countries);
        Countries.$inject = [];
        function Countries(){

          var list = [ // Taken from https://gist.github.com/unceus/6501985
                        {name: 'Angola', continent: 'Africa'},
                        {name: 'Argelia', continent: 'Africa'},
                        {name: 'Benin', continent: 'Africa'},
                        {name: 'Botsuana', continent: 'Africa'},
                        {name: 'Burkina Faso', continent: 'Africa'},
                        {name: 'Burundi', continent: 'Africa'},
                        {name: 'Cabo Verde', continent: 'Africa'},
                        {name: 'Camerun', continent: 'Africa'},
                        {name: 'Chad', continent: 'Africa'},
                        {name: 'Comoras', continent: 'Africa'},
                        {name: 'Congo', continent: 'Africa'},
                        {name: 'Costa de Marfil', continent: 'Africa'},
                        {name: 'Egipto', continent: 'Africa'},
                        {name: 'Eritrea', continent: 'Africa'},
                        {name: 'Etiopia', continent: 'Africa'},
                        {name: 'Gabon', continent: 'Africa'},
                        {name: 'Gambia', continent: 'Africa'},
                        {name: 'Ghana', continent: 'Africa'},
                        {name: 'Guinea', continent: 'Africa'},
                        {name: 'Kenia', continent: 'Africa'},
                        {name: 'Liberia', continent: 'Africa'},
                        {name: 'Madagascar', continent: 'Africa'},
                        {name: 'Malaui', continent: 'Africa'},
                        {name: 'Marruecos', continent: 'Africa'},
                        {name: 'Nigeria', continent: 'Africa'},
                        {name: 'Ruanda', continent: 'Africa'},
                        {name: 'Senegal', continent: 'Africa'},
                        {name: 'Serria Leona', continent: 'Africa'},
                        {name: 'Sudafrica', continent: 'Africa'},
                        {name: 'Angola', continent: 'Africa'},
                        {name: 'Sudan', continent: 'Africa'},
                        {name: 'Togo', continent: 'Africa'},
                        {name: 'Tunez', continent: 'Africa'},
                        {name: 'Uganda', continent: 'Africa'},
                        {name: 'Ybuti', continent: 'Africa'},
                        {name: 'Zambia', continent: 'Africa'},
                        {name: 'Zimbabue', continent: 'Africa'},
                        {name: 'Bermudas', continent: 'North America'},
                        {name: 'Canada', continent: 'North America'},
                        {name: 'Estados Unidos', continent: 'North America'},
                        {name: 'Mexico', continent: 'North America'},
                        {name: 'Groenlandia', continent: 'North America'},
                        {name: 'Belice', continent: 'Central America'},
                        {name: 'Salvador', continent: 'Central America'},
                        {name: 'Costa Rica', continent: 'Central America'},
                        {name: 'Nicaragua', continent: 'Central America'},
                        {name: 'Panama', continent: 'Central America'},
                        {name: 'Honduras', continent: 'Central America'},
                        {name: 'Guatemala', continent: 'Central America'},
                        {name: 'Argentina', continent: 'South America'},
                        {name: 'Bolivia', continent: 'South America'},
                        {name: 'Brasil', continent: 'South America'},
                        {name: 'Chile', continent: 'South America'},
                        {name: 'Colombia', continent: 'South America'},
                        {name: 'Ecuador', continent: 'South America'},
                        {name: 'Guyana Francesa', continent: 'South America'},
                        {name: 'Guyana', continent: 'South America'},
                        {name: 'Paraguay', continent: 'South America'},
                        {name: 'Peru', continent: 'South America'},
                        {name: 'Surinam', continent: 'South America'},
                        {name: 'Uruguay', continent: 'South America'},
                        {name: 'Venezuela', continent: 'South America'},
                        {name: 'Aruba', continent: 'Antillas'},
                        {name: 'Bahamas', continent: 'Antillas'},
                        {name: 'Barbados', continent: 'Antillas'},
                        {name: 'Anguila', continent: 'Antillas'},
                        {name: 'Cuba', continent: 'Antillas'},
                        {name: 'Curazao', continent: 'Antillas'},
                        {name: 'Dominica', continent: 'Antillas'},
                        {name: 'Granada', continent: 'Antillas'},
                        {name: 'Guadalupe', continent: 'Antillas'},
                        {name: 'Haiti', continent: 'Antillas'},
                        {name: 'Islas Caiman', continent: 'Antillas'},
                        {name: 'Jamaica', continent: 'Antillas'},
                        {name: 'Martinica', continent: 'Antillas'},
                        {name: 'Montserrat', continent: 'Antillas'},
                        {name: 'Puerto Rico', continent: 'Antillas'},
                        {name: 'Republica Dominicana', continent: 'Antillas'},
                        {name: 'San Bartolome', continent: 'Antillas'},
                        {name: 'San Martin', continent: 'Antillas'},
                        {name: 'Santa Lucia', continent: 'Antillas'},
                        {name: 'Trinidad y Tobago', continent: 'Antillas'},
                        {name: 'Afganistan', continent: 'Asia'},
                        {name: 'Arabia Saudita', continent: 'Asia'},
                        {name: 'Armenia', continent: 'Asia'},
                        {name: 'Azerbaiyan', continent: 'Asia'},
                        {name: 'Barein', continent: 'Asia'},
                        {name: 'Bangladesh', continent: 'Asia'},
                        {name: 'Camboya', continent: 'Asia'},
                        {name: 'China', continent: 'Asia'},
                        {name: 'Corea del Norte', continent: 'Asia'},
                        {name: 'Corea del Sur', continent: 'Asia'},
                        {name: 'Filipinas', continent: 'Asia'},
                        {name: 'India', continent: 'Asia'},
                        {name: 'Indonesia', continent: 'Asia'},
                        {name: 'Irak', continent: 'Asia'},
                        {name: 'Iran', continent: 'Asia'},
                        {name: 'Israel', continent: 'Asia'},
                        {name: 'Japon', continent: 'Asia'},
                        {name: 'Jordania', continent: 'Asia'},
                        {name: 'Kazajistan', continent: 'Asia'},
                        {name: 'Kuwait', continent: 'Asia'},
                        {name: 'Laos', continent: 'Asia'},
                        {name: 'Libano', continent: 'Asia'},
                        {name: 'Macao', continent: 'Asia'},
                        {name: 'Malasia', continent: 'Asia'},
                        {name: 'Maldivas', continent: 'Asia'},
                        {name: 'Mongolia', continent: 'Asia'},
                        {name: 'Oman', continent: 'Asia'},
                        {name: 'Pakistan', continent: 'Asia'},
                        {name: 'Qatar', continent: 'Asia'},
                        {name: 'Rusia', continent: 'Asia'},
                        {name: 'Singapur', continent: 'Asia'},
                        {name: 'Siria', continent: 'Asia'},
                        {name: 'Sri Lanka', continent: 'Asia'},
                        {name: 'Tailandia', continent: 'Asia'},
                        {name: 'Turkia', continent: 'Asia'},
                        {name: 'Vietnam', continent: 'Asia'},
                        {name: 'Yemen', continent: 'Asia'},
                        {name: 'Albania', continent: 'Europe'},
                        {name: 'Alemania', continent: 'Europe'},
                        {name: 'Andorra', continent: 'Europe'},
                        {name: 'Austria', continent: 'Europe'},
                        {name: 'Belgica', continent: 'Europe'},
                        {name: 'Bulgaria', continent: 'Europe'},
                        {name: 'Chipre', continent: 'Europe'},
                        {name: 'Croacia', continent: 'Europe'},
                        {name: 'Dinamarca', continent: 'Europe'},
                        {name: 'Eslovaquia', continent: 'Europe'},
                        {name: 'Eslovenia', continent: 'Europe'},
                        {name: 'España', continent: 'Europe'},
                        {name: 'Estonia', continent: 'Europe'},
                        {name: 'Finlandia', continent: 'Europe'},
                        {name: 'Francia', continent: 'Europe'},
                        {name: 'Georgia', continent: 'Europe'},
                        {name: 'Gibraltar', continent: 'Europe'},
                        {name: 'Grecia', continent: 'Europe'},
                        {name: 'Hungria', continent: 'Europe'},
                        {name: 'Irlanda', continent: 'Europe'},
                        {name: 'Islandia', continent: 'Europe'},
                        {name: 'Italia', continent: 'Europe'},
                        {name: 'Letonia', continent: 'Europe'},
                        {name: 'Lituania', continent: 'Europe'},
                        {name: 'Luxemburgo', continent: 'Europe'},
                        {name: 'Malta', continent: 'Europe'},
                        {name: 'Moldavia', continent: 'Europe'},
                        {name: 'Noruega', continent: 'Europe'},
                        {name: 'Polonia', continent: 'Europe'},
                        {name: 'Portugal', continent: 'Europe'},
                        {name: 'Inglaterra', continent: 'Europe'},
                        {name: 'Gales', continent: 'Europe'},
                        {name: 'Escocia', continent: 'Europe'},
                        {name: 'Republica Checa', continent: 'Europe'},
                        {name: 'Rumania', continent: 'Europe'},
                        {name: 'San Marino', continent: 'Europe'},
                        {name: 'Serbia', continent: 'Europe'},
                        {name: 'Suecia', continent: 'Europe'},
                        {name: 'Suiza', continent: 'Europe'},
                        {name: 'Ucrania', continent: 'Europe'},
                        {name: 'Australia', continent: 'Oceania'},
                        {name: 'Palaos', continent: 'Oceania'},
                        {name: 'Samoa', continent: 'Oceania'},
                        {name: 'Tonga', continent: 'Oceania'},
                        {name: 'Tuvalu', continent: 'Oceania'}
                      ]

            return {
              list: list
            }
        }
})();
