(function(){
  'use strict';
    angular
        .module('angular')
        .factory('LocationAutoComplete', LocationAutoComplete);
        LocationAutoComplete.$inject = [];
        function LocationAutoComplete(){

          var countries = [
                {name: 'Angola', continent: 'Africa'},
                {name: 'Argelia', continent: 'Africa'},
                {name: 'Benin', continent: 'Africa'},
                {name: 'Botsuana', continent: 'Africa'},
                {name: 'Burkina Faso', continent: 'Africa'},
                {name: 'Burundi', continent: 'Africa'},
                {name: 'Cabo Verde', continent: 'Africa'},
                {name: 'Camerun', continent: 'Africa'},
                {name: 'Chad', continent: 'Africa'},
                {name: 'Comoras', continent: 'Africa'},
                {name: 'Congo', continent: 'Africa'},
                {name: 'Costa de Marfil', continent: 'Africa'},
                {name: 'Egipto', continent: 'Africa'},
                {name: 'Eritrea', continent: 'Africa'},
                {name: 'Etiopia', continent: 'Africa'},
                {name: 'Gabon', continent: 'Africa'},
                {name: 'Gambia', continent: 'Africa'},
                {name: 'Ghana', continent: 'Africa'},
                {name: 'Guinea', continent: 'Africa'},
                {name: 'Kenia', continent: 'Africa'},
                {name: 'Liberia', continent: 'Africa'},
                {name: 'Madagascar', continent: 'Africa'},
                {name: 'Malaui', continent: 'Africa'},
                {name: 'Marruecos', continent: 'Africa'},
                {name: 'Nigeria', continent: 'Africa'},
                {name: 'Ruanda', continent: 'Africa'},
                {name: 'Senegal', continent: 'Africa'},
                {name: 'Serria Leona', continent: 'Africa'},
                {name: 'Sudafrica', continent: 'Africa'},
                {name: 'Angola', continent: 'Africa'},
                {name: 'Sudan', continent: 'Africa'},
                {name: 'Togo', continent: 'Africa'},
                {name: 'Tunez', continent: 'Africa'},
                {name: 'Uganda', continent: 'Africa'},
                {name: 'Ybuti', continent: 'Africa'},
                {name: 'Zambia', continent: 'Africa'},
                {name: 'Zimbabue', continent: 'Africa'},
                {name: 'Bermudas', continent: 'North America'},
                {name: 'Canada', continent: 'North America'},
                {name: 'Estados Unidos', continent: 'North America'},
                {name: 'Mexico', continent: 'North America'},
                {name: 'Groenlandia', continent: 'North America'},
                {name: 'Belice', continent: 'Central America'},
                {name: 'Salvador', continent: 'Central America'},
                {name: 'Costa Rica', continent: 'Central America'},
                {name: 'Nicaragua', continent: 'Central America'},
                {name: 'Panama', continent: 'Central America'},
                {name: 'Honduras', continent: 'Central America'},
                {name: 'Guatemala', continent: 'Central America'},
                {name: 'Argentina', continent: 'South America'},
                {name: 'Bolivia', continent: 'South America'},
                {name: 'Brasil', continent: 'South America'},
                {name: 'Chile', continent: 'South America'},
                {name: 'Colombia', continent: 'South America'},
                {name: 'Ecuador', continent: 'South America'},
                {name: 'Guyana Francesa', continent: 'South America'},
                {name: 'Guyana', continent: 'South America'},
                {name: 'Paraguay', continent: 'South America'},
                {name: 'Peru', continent: 'South America'},
                {name: 'Surinam', continent: 'South America'},
                {name: 'Uruguay', continent: 'South America'},
                {name: 'Venezuela', continent: 'South America'},
                {name: 'Aruba', continent: 'Antillas'},
                {name: 'Bahamas', continent: 'Antillas'},
                {name: 'Barbados', continent: 'Antillas'},
                {name: 'Anguila', continent: 'Antillas'},
                {name: 'Cuba', continent: 'Antillas'},
                {name: 'Curazao', continent: 'Antillas'},
                {name: 'Dominica', continent: 'Antillas'},
                {name: 'Granada', continent: 'Antillas'},
                {name: 'Guadalupe', continent: 'Antillas'},
                {name: 'Haiti', continent: 'Antillas'},
                {name: 'Islas Caiman', continent: 'Antillas'},
                {name: 'Jamaica', continent: 'Antillas'},
                {name: 'Martinica', continent: 'Antillas'},
                {name: 'Montserrat', continent: 'Antillas'},
                {name: 'Puerto Rico', continent: 'Antillas'},
                {name: 'Republica Dominicana', continent: 'Antillas'},
                {name: 'San Bartolome', continent: 'Antillas'},
                {name: 'San Martin', continent: 'Antillas'},
                {name: 'Santa Lucia', continent: 'Antillas'},
                {name: 'Trinidad y Tobago', continent: 'Antillas'},
                {name: 'Afganistan', continent: 'Asia'},
                {name: 'Arabia Saudita', continent: 'Asia'},
                {name: 'Armenia', continent: 'Asia'},
                {name: 'Azerbaiyan', continent: 'Asia'},
                {name: 'Barein', continent: 'Asia'},
                {name: 'Bangladesh', continent: 'Asia'},
                {name: 'Camboya', continent: 'Asia'},
                {name: 'China', continent: 'Asia'},
                {name: 'Corea del Norte', continent: 'Asia'},
                {name: 'Corea del Sur', continent: 'Asia'},
                {name: 'Filipinas', continent: 'Asia'},
                {name: 'India', continent: 'Asia'},
                {name: 'Indonesia', continent: 'Asia'},
                {name: 'Irak', continent: 'Asia'},
                {name: 'Iran', continent: 'Asia'},
                {name: 'Israel', continent: 'Asia'},
                {name: 'Japon', continent: 'Asia'},
                {name: 'Jordania', continent: 'Asia'},
                {name: 'Kazajistan', continent: 'Asia'},
                {name: 'Kuwait', continent: 'Asia'},
                {name: 'Laos', continent: 'Asia'},
                {name: 'Libano', continent: 'Asia'},
                {name: 'Macao', continent: 'Asia'},
                {name: 'Malasia', continent: 'Asia'},
                {name: 'Maldivas', continent: 'Asia'},
                {name: 'Mongolia', continent: 'Asia'},
                {name: 'Oman', continent: 'Asia'},
                {name: 'Pakistan', continent: 'Asia'},
                {name: 'Qatar', continent: 'Asia'},
                {name: 'Rusia', continent: 'Asia'},
                {name: 'Singapur', continent: 'Asia'},
                {name: 'Siria', continent: 'Asia'},
                {name: 'Sri Lanka', continent: 'Asia'},
                {name: 'Tailandia', continent: 'Asia'},
                {name: 'Turkia', continent: 'Asia'},
                {name: 'Vietnam', continent: 'Asia'},
                {name: 'Yemen', continent: 'Asia'},
                {name: 'Albania', continent: 'Europe'},
                {name: 'Alemania', continent: 'Europe'},
                {name: 'Andorra', continent: 'Europe'},
                {name: 'Austria', continent: 'Europe'},
                {name: 'Belgica', continent: 'Europe'},
                {name: 'Bulgaria', continent: 'Europe'},
                {name: 'Chipre', continent: 'Europe'},
                {name: 'Croacia', continent: 'Europe'},
                {name: 'Dinamarca', continent: 'Europe'},
                {name: 'Eslovaquia', continent: 'Europe'},
                {name: 'Eslovenia', continent: 'Europe'},
                {name: 'España', continent: 'Europe'},
                {name: 'Estonia', continent: 'Europe'},
                {name: 'Finlandia', continent: 'Europe'},
                {name: 'Francia', continent: 'Europe'},
                {name: 'Georgia', continent: 'Europe'},
                {name: 'Gibraltar', continent: 'Europe'},
                {name: 'Grecia', continent: 'Europe'},
                {name: 'Hungria', continent: 'Europe'},
                {name: 'Irlanda', continent: 'Europe'},
                {name: 'Islandia', continent: 'Europe'},
                {name: 'Italia', continent: 'Europe'},
                {name: 'Letonia', continent: 'Europe'},
                {name: 'Lituania', continent: 'Europe'},
                {name: 'Luxemburgo', continent: 'Europe'},
                {name: 'Malta', continent: 'Europe'},
                {name: 'Moldavia', continent: 'Europe'},
                {name: 'Noruega', continent: 'Europe'},
                {name: 'Polonia', continent: 'Europe'},
                {name: 'Portugal', continent: 'Europe'},
                {name: 'Inglaterra', continent: 'Europe'},
                {name: 'Gales', continent: 'Europe'},
                {name: 'Escocia', continent: 'Europe'},
                {name: 'Republica Checa', continent: 'Europe'},
                {name: 'Rumania', continent: 'Europe'},
                {name: 'San Marino', continent: 'Europe'},
                {name: 'Serbia', continent: 'Europe'},
                {name: 'Suecia', continent: 'Europe'},
                {name: 'Suiza', continent: 'Europe'},
                {name: 'Ucrania', continent: 'Europe'},
                {name: 'Australia', continent: 'Oceania'},
                {name: 'Palaos', continent: 'Oceania'},
                {name: 'Samoa', continent: 'Oceania'},
                {name: 'Tonga', continent: 'Oceania'},
                {name: 'Tuvalu', continent: 'Oceania'}
              ];

            var costaRicaProvinces = [
              {name: 'San José'},
              {name: 'Alajuela'},
              {name: 'Cartago'},
              {name: 'Heredia'},
              {name: 'Guanacaste'},
              {name: 'Puntarenas'},
              {name: 'Limón'}
            ]

            var costaRicaStates = [
              {province: 'San José', name: 'San José'},
              {province: 'San José', name: 'Escazú'},
              {province: 'San José', name: 'Desamparados'},
              {province: 'San José', name: 'Puriscal'},
              {province: 'San José', name: 'Tarrazú'},
              {province: 'San José', name: 'Aserrí'},
              {province: 'San José', name: 'Mora'},
              {province: 'San José', name: 'Goicoechea'},
              {province: 'San José', name: 'Santa Ana'},
              {province: 'San José', name: 'Alajuelita'},
              {province: 'San José', name: 'Vásquez de Coronado'},
              {province: 'San José', name: 'Acosta'},
              {province: 'San José', name: 'Tibás'},
              {province: 'San José', name: 'Moravia'},
              {province: 'San José', name: 'Montes de Oca'},
              {province: 'San José', name: 'Turrubares'},
              {province: 'San José', name: 'Dota'},
              {province: 'San José', name: 'Curridabat'},
              {province: 'San José', name: 'Pérez Zeledón'},
              {province: 'San José', name: 'León Cortés'},
              {province: 'Alajuela', name: 'Alajuela'},
              {province: 'Alajuela', name: 'San Ramón'},
              {province: 'Alajuela', name: 'Grecia'},
              {province: 'Alajuela', name: 'San Mateo'},
              {province: 'Alajuela', name: 'Atenas'},
              {province: 'Alajuela', name: 'Naranjo'},
              {province: 'Alajuela', name: 'Palmares'},
              {province: 'Alajuela', name: 'Poás'},
              {province: 'Alajuela', name: 'Orotina'},
              {province: 'Alajuela', name: 'San Carlos'},
              {province: 'Alajuela', name: 'Zarcero'},
              {province: 'Alajuela', name: 'Valverde Vega'},
              {province: 'Alajuela', name: 'Upala'},
              {province: 'Alajuela', name: 'Los Chiles'},
              {province: 'Alajuela', name: 'Guatuso'},
              {province: 'Cartago', name: 'Cartago'},
              {province: 'Cartago', name: 'Paraíso'},
              {province: 'Cartago', name: 'La Unión'},
              {province: 'Cartago', name: 'Jiménez'},
              {province: 'Cartago', name: 'Turrialba'},
              {province: 'Cartago', name: 'Alvarado'},
              {province: 'Cartago', name: 'Oreamuno'},
              {province: 'Cartago', name: 'El Guarco'},
              {province: 'Heredia', name: 'Heredia'},
              {province: 'Heredia', name: 'Barva'},
              {province: 'Heredia', name: 'Santo Domingo'},
              {province: 'Heredia', name: 'Santa Bárbara'},
              {province: 'Heredia', name: 'San Rafael'},
              {province: 'Heredia', name: 'San Isidro'},
              {province: 'Heredia', name: 'Belén'},
              {province: 'Heredia', name: 'Flores'},
              {province: 'Heredia', name: 'San Pablo'},
              {province: 'Heredia', name: 'Sarapiquí'},
              {province: 'Guanacaste', name: 'Liberia'},
              {province: 'Guanacaste', name: 'Nicoya'},
              {province: 'Guanacaste', name: 'Santa Cruz'},
              {province: 'Guanacaste', name: 'Bagaces'},
              {province: 'Guanacaste', name: 'Carrillo'},
              {province: 'Guanacaste', name: 'Cañas'},
              {province: 'Guanacaste', name: 'Abangares'},
              {province: 'Guanacaste', name: 'Tilarán'},
              {province: 'Guanacaste', name: 'Nandayure'},
              {province: 'Guanacaste', name: 'La Cruz'},
              {province: 'Guanacaste', name: 'Hojancha'},
              {province: 'Puntarenas', name: 'Puntarenas'},
              {province: 'Puntarenas', name: 'Esparza'},
              {province: 'Puntarenas', name: 'Buenos Aires'},
              {province: 'Puntarenas', name: 'Montes de Oro'},
              {province: 'Puntarenas', name: 'Osa'},
              {province: 'Puntarenas', name: 'Quepos'},
              {province: 'Puntarenas', name: 'Golfito'},
              {province: 'Puntarenas', name: 'Coto Brus'},
              {province: 'Puntarenas', name: 'Parrita'},
              {province: 'Puntarenas', name: 'Corredores'},
              {province: 'Puntarenas', name: 'Garabito'},
              {province: 'Limón', name: 'Limón'},
              {province: 'Limón', name: 'Pococí'},
              {province: 'Limón', name: 'Siquirres'},
              {province: 'Limón', name: 'Talamanca'},
              {province: 'Limón', name: 'Matina'},
              {province: 'Limón', name: 'Guácimo'}
            ];

            var costaRicaCities = [
              {state: 'San José', name: 'El Carmen' },
              {state: 'San José', name: 'Merced' },
              {state: 'San José', name: 'Hospital' },
              {state: 'San José', name: 'Catedral' },
              {state: 'San José', name: 'Zapote' },
              {state: 'San José', name: 'San Francisco de Dos Ríos' },
              {state: 'San José', name: 'Uruca' },
              {state: 'San José', name: 'Mata Redonda' },
              {state: 'San José', name: 'Pavas' },
              {state: 'San José', name: 'Hatillo' },
              {state: 'San José', name: 'San Sebastián' },
              {state: 'Escazú', name: 'Escazú' },
              {state: 'Escazú', name: 'San Antonio' },
              {state: 'Escazú', name: 'San Rafael' },
              {state: 'Desamparados', name: 'Desamparados' },
              {state: 'Desamparados', name: 'San Miguel' },
              {state: 'Desamparados', name: 'San Juan de Dios' },
              {state: 'Desamparados', name: 'San Rafael Arriba' },
              {state: 'Desamparados', name: 'San Antonio' },
              {state: 'Desamparados', name: 'Frailes' },
              {state: 'Desamparados', name: 'Patarrá' },
              {state: 'Desamparados', name: 'San Cristóbal' },
              {state: 'Desamparados', name: 'Rosario' },
              {state: 'Desamparados', name: 'Damas' },
              {state: 'Desamparados', name: 'San Rafael Abajo' },
              {state: 'Desamparados', name: 'Gravilias' },
              {state: 'Puriscal', name: 'Santiago' },
              {state: 'Puriscal', name: 'Mercedes Sur' },
              {state: 'Puriscal', name: 'Barbacoas' },
              {state: 'Puriscal', name: 'Grifo Alto' },
              {state: 'Puriscal', name: 'San Rafael' },
              {state: 'Puriscal', name: 'Candelarita' },
              {state: 'Puriscal', name: 'Desamparaditos' },
              {state: 'Puriscal', name: 'San Antonio' },
              {state: 'Puriscal', name: 'Chires' },
              {state: 'Tarrazú', name: 'San Marcos' },
              {state: 'Tarrazú', name: 'San Lorenzo' },
              {state: 'Tarrazú', name: 'San Carlos' },
              {state: 'Aserrí', name: 'Aserrí' },
              {state: 'Aserrí', name: 'Tarbaca' },
              {state: 'Aserrí', name: 'Vuelta de Jorco' },
              {state: 'Aserrí', name: 'San Gabriel' },
              {state: 'Aserrí', name: 'Legua' },
              {state: 'Aserrí', name: 'Monterrey' },
              {state: 'Aserrí', name: 'Salitrillos' },
              {state: 'Mora', name: 'Colón' },
              {state: 'Mora', name: 'Guayabo' },
              {state: 'Mora', name: 'Tabarcia' },
              {state: 'Mora', name: 'Piedras Negras' },
              {state: 'Mora', name: 'Picagres' },
              {state: 'Goicoechea', name: 'Guadalupe' },
              {state: 'Goicoechea', name: 'San Francisco' },
              {state: 'Goicoechea', name: 'Calle Blancos' },
              {state: 'Goicoechea', name: 'Mata de Plátano' },
              {state: 'Goicoechea', name: 'Ipís' },
              {state: 'Goicoechea', name: 'Rancho Redondo' },
              {state: 'Goicoechea', name: 'Purral' },
              {state: 'Santa Ana', name: 'Santa Ana' },
              {state: 'Santa Ana', name: 'Salitral' },
              {state: 'Santa Ana', name: 'Pozos' },
              {state: 'Santa Ana', name: 'Uruca' },
              {state: 'Santa Ana', name: 'Piedades' },
              {state: 'Santa Ana', name: 'Brasil' },
              {state: 'Alajuelita', name: 'Alajuelita' },
              {state: 'Alajuelita', name: 'San Josecito' },
              {state: 'Alajuelita', name: 'San Antonio' },
              {state: 'Alajuelita', name: 'Concepción' },
              {state: 'Alajuelita', name: 'San Felipe' },
              {state: 'Vásquez de Coronado', name: 'San Isidro' },
              {state: 'Vásquez de Coronado', name: 'San Rafael' },
              {state: 'Vásquez de Coronado', name: 'Dulce Nombre de Jesús' },
              {state: 'Vásquez de Coronado', name: 'Patalillo' },
              {state: 'Vásquez de Coronado', name: 'Cascajal' },
              {state: 'Acosta', name: 'San Ignacio' },
              {state: 'Acosta', name: 'Guaitíl' },
              {state: 'Acosta', name: 'Palmichal' },
              {state: 'Acosta', name: 'Cangrejal' },
              {state: 'Acosta', name: 'Sabanillas' },
              {state: 'Tibás', name: 'San Juan' },
              {state: 'Tibás', name: 'Cinco Esquinas' },
              {state: 'Tibás', name: 'Anselmo Llorente' },
              {state: 'Tibás', name: 'León XIII' },
              {state: 'Tibás', name: 'Colima' },
              {state: 'Moravia', name: 'San Vicente' },
              {state: 'Moravia', name: 'San Jerónimo' },
              {state: 'Moravia', name: 'Trinidad' },
              {state: 'Montes de Oca', name: 'San Pedro' },
              {state: 'Montes de Oca', name: 'Sabanilla' },
              {state: 'Montes de Oca', name: 'Mercedes' },
              {state: 'Montes de Oca', name: 'San Rafael' },
              {state: 'Turrubares', name: 'San Pablo' },
              {state: 'Turrubares', name: 'San Pedro' },
              {state: 'Turrubares', name: 'San Juan de Mata' },
              {state: 'Turrubares', name: 'San Luis' },
              {state: 'Dota', name: 'Santa María' },
              {state: 'Dota', name: 'Jardín' },
              {state: 'Dota', name: 'Copey' },
              {state: 'Curridabat', name: 'Curridabat' },
              {state: 'Curridabat', name: 'Granadilla' },
              {state: 'Curridabat', name: 'Sánchez' },
              {state: 'Curridabat', name: 'Tirrases' },
              {state: 'Perez Zeledón', name: 'San Isidro de El General' },
              {state: 'Perez Zeledón', name: 'General' },
              {state: 'Perez Zeledón', name: 'Daniel Flores' },
              {state: 'Perez Zeledón', name: 'Rivas' },
              {state: 'Perez Zeledón', name: 'San Pedro' },
              {state: 'Perez Zeledón', name: 'Platanares' },
              {state: 'Perez Zeledón', name: 'Pejibaye' },
              {state: 'Perez Zeledón', name: 'Cajón' },
              {state: 'Perez Zeledón', name: 'Barú' },
              {state: 'Perez Zeledón', name: 'Río Nuevo' },
              {state: 'Perez Zeledón', name: 'Páramo' },
              {state: 'León Cortés', name: 'San Pablo' },
              {state: 'León Cortés', name: 'San Andrés' },
              {state: 'León Cortés', name: 'Llano Bonito' },
              {state: 'León Cortés', name: 'San Isidro' },
              {state: 'León Cortés', name: 'Santa Cruz' },
              {state: 'León Cortés', name: 'San Antonio' },
              {state: 'Alajuela', name: 'Alajuela' },
              {state: 'Alajuela', name: 'San José' },
              {state: 'Alajuela', name: 'Carrizal' },
              {state: 'Alajuela', name: 'San Antonio' },
              {state: 'Alajuela', name: 'Guácima' },
              {state: 'Alajuela', name: 'San Isidro' },
              {state: 'Alajuela', name: 'Sabanilla' },
              {state: 'Alajuela', name: 'San Rafael' },
              {state: 'Alajuela', name: 'Río Segundo' },
              {state: 'Alajuela', name: 'Desamparados' },
              {state: 'Alajuela', name: 'Turrúcares' },
              {state: 'Alajuela', name: 'Tambor' },
              {state: 'Alajuela', name: 'La Garita' },
              {state: 'Alajuela', name: 'Sarapiquí' },
              {state: 'San Ramón', name: 'San Ramón' },
              {state: 'San Ramón', name: 'Santiago' },
              {state: 'San Ramón', name: 'San Juan' },
              {state: 'San Ramón', name: 'Piedades Norte' },
              {state: 'San Ramón', name: 'Piedades Sur' },
              {state: 'San Ramón', name: 'San Rafael' },
              {state: 'San Ramón', name: 'San Isidro' },
              {state: 'San Ramón', name: 'Angeles' },
              {state: 'San Ramón', name: 'Alfaro' },
              {state: 'San Ramón', name: 'Volio' },
              {state: 'San Ramón', name: 'Concepción' },
              {state: 'San Ramón', name: 'Zapotal' },
              {state: 'San Ramón', name: 'Peñas Blancas' },
              {state: 'Grecia', name: 'Grecia' },
              {state: 'Grecia', name: 'San Isidro' },
              {state: 'Grecia', name: 'San José' },
              {state: 'Grecia', name: 'San Roque' },
              {state: 'Grecia', name: 'Tacares' },
              {state: 'Grecia', name: 'Río Cuarto' },
              {state: 'Grecia', name: 'Puente de Piedra' },
              {state: 'Grecia', name: 'Bolívar' },
              {state: 'San Mateo', name: 'San Mateo' },
              {state: 'San Mateo', name: 'Desmonte' },
              {state: 'San Mateo', name: 'Jesús María' },
              {state: 'Atenas', name: 'Atenas' },
              {state: 'Atenas', name: 'Jesús' },
              {state: 'Atenas', name: 'Mercedes' },
              {state: 'Atenas', name: 'San Isidro' },
              {state: 'Atenas', name: 'Concepción' },
              {state: 'Atenas', name: 'San José' },
              {state: 'Atenas', name: 'Santa Eulalia' },
              {state: 'Naranjo', name: 'Naranjo' },
              {state: 'Naranjo', name: 'San Miguel' },
              {state: 'Naranjo', name: 'San José' },
              {state: 'Naranjo', name: 'Cirrí Sur' },
              {state: 'Naranjo', name: 'San Jerónimo' },
              {state: 'Naranjo', name: 'San Juan' },
              {state: 'Naranjo', name: 'Rosario' },
              {state: 'Palmares', name: 'Palmares' },
              {state: 'Palmares', name: 'Zaragoza' },
              {state: 'Palmares', name: 'Buenos Aires' },
              {state: 'Palmares', name: 'Santiago' },
              {state: 'Palmares', name: 'Candelaria' },
              {state: 'Palmares', name: 'Esquipulas' },
              {state: 'Palmares', name: 'Granja' },
              {state: 'Poás', name: 'San Pedro' },
              {state: 'Poás', name: 'San Juan' },
              {state: 'Poás', name: 'San Rafael' },
              {state: 'Poás', name: 'Carrillos' },
              {state: 'Poás', name: 'Sabana Redonda' },
              {state: 'Orotina', name: 'Orotina' },
              {state: 'Orotina', name: 'Mastate' },
              {state: 'Orotina', name: 'Hacienda Vieja' },
              {state: 'Orotina', name: 'Coyolar' },
              {state: 'Orotina', name: 'Ceiba' },
              {state: 'San Carlos', name: 'Quesada' },
              {state: 'San Carlos', name: 'Florencia' },
              {state: 'San Carlos', name: 'Buenavista' },
              {state: 'San Carlos', name: 'Aguas Zarcas' },
              {state: 'San Carlos', name: 'Venecia' },
              {state: 'San Carlos', name: 'Pital' },
              {state: 'San Carlos', name: 'Fortuna' },
              {state: 'San Carlos', name: 'Tigra' },
              {state: 'San Carlos', name: 'Palmera' },
              {state: 'San Carlos', name: 'Venado' },
              {state: 'San Carlos', name: 'Cutris' },
              {state: 'San Carlos', name: 'Monterrey' },
              {state: 'San Carlos', name: 'Pocosol' },
              {state: 'Zarcero', name: 'Zarcero' },
              {state: 'Zarcero', name: 'Laguna' },
              {state: 'Zarcero', name: 'Tapezco' },
              {state: 'Zarcero', name: 'Guadalupe' },
              {state: 'Zarcero', name: 'Palmira' },
              {state: 'Zarcero', name: 'Zapote' },
              {state: 'Zarcero', name: 'Brisas' },
              {state: 'Valverde Vega', name: 'Sarchí Norte' },
              {state: 'Valverde Vega', name: 'Sarchí Sur' },
              {state: 'Valverde Vega', name: 'Toro Amarillo' },
              {state: 'Valverde Vega', name: 'San Pedro' },
              {state: 'Valverde Vega', name: 'Rodríguez' },
              {state: 'Upala', name: 'Upala' },
              {state: 'Upala', name: 'Aguas Claras' },
              {state: 'Upala', name: 'San José o Pizote' },
              {state: 'Upala', name: 'Bijagua' },
              {state: 'Upala', name: 'Delicias' },
              {state: 'Upala', name: 'Dos Ríos' },
              {state: 'Upala', name: 'Yolillal' },
              {state: 'Los Chiles', name: 'Los Chiles' },
              {state: 'Los Chiles', name: 'Caño Negro' },
              {state: 'Los Chiles', name: 'El Amparo' },
              {state: 'Los Chiles', name: 'San Jorge' },
              {state: 'Guatuso', name: 'San Rafael' },
              {state: 'Guatuso', name: 'Buenavista' },
              {state: 'Guatuso', name: 'Cote' },
              {state: 'Cartago', name: 'Oriental' },
              {state: 'Cartago', name: 'Occidental' },
              {state: 'Cartago', name: 'Carmen' },
              {state: 'Cartago', name: 'San Nicolás' },
              {state: 'Cartago', name: 'Aguacaliente o San Fco.' },
              {state: 'Cartago', name: 'Guadalupe o Arenilla' },
              {state: 'Cartago', name: 'Corralillo' },
              {state: 'Cartago', name: 'Tierra Blanca' },
              {state: 'Cartago', name: 'Dulce Nombre' },
              {state: 'Cartago', name: 'Llano Grande' },
              {state: 'Cartago', name: 'Quebradilla' },
              {state: 'Paraíso', name: 'Paraíso' },
              {state: 'Paraíso', name: 'Santiago' },
              {state: 'Paraíso', name: 'Orosi' },
              {state: 'Paraíso', name: 'Cachí' },
              {state: 'La Unión', name: 'Tres Ríos' },
              {state: 'La Unión', name: 'San Diego' },
              {state: 'La Unión', name: 'San Juan' },
              {state: 'La Unión', name: 'San Rafael' },
              {state: 'La Unión', name: 'Concepción' },
              {state: 'La Unión', name: 'Dulce Nombre' },
              {state: 'La Unión', name: 'San Ramón' },
              {state: 'La Unión', name: 'Río Azul' },
              {state: 'La Unión', name: 'JIMENEZ' },
              {state: 'La Unión', name: 'Juan Viñas' },
              {state: 'La Unión', name: 'Tucurrique' },
              {state: 'La Unión', name: 'Pejibaye' },
              {state: 'Turrialba', name: 'Turrialba' },
              {state: 'Turrialba', name: 'La Suiza' },
              {state: 'Turrialba', name: 'Peralta' },
              {state: 'Turrialba', name: 'Santa Cruz' },
              {state: 'Turrialba', name: 'Santa Teresita' },
              {state: 'Turrialba', name: 'Pavones' },
              {state: 'Turrialba', name: 'Tuis' },
              {state: 'Turrialba', name: 'Tayutic' },
              {state: 'Turrialba', name: 'Santa Rosa' },
              {state: 'Turrialba', name: 'Tres Equis' },
              {state: 'Alvarado', name: 'Pacayas' },
              {state: 'Alvarado', name: 'Cervantes' },
              {state: 'Alvarado', name: 'Capellades' },
              {state: 'Oreamuno', name: 'San Rafael' },
              {state: 'Oreamuno', name: 'Cot' },
              {state: 'Oreamuno', name: 'Potrero Cerrado' },
              {state: 'Oreamuno', name: 'Cipreses' },
              {state: 'Oreamuno', name: 'Santa Rosa' },
              {state: 'El Guarco', name: 'El Tejar' },
              {state: 'El Guarco', name: 'San Isidro' },
              {state: 'El Guarco', name: 'Tobosi' },
              {state: 'El Guarco', name: 'Patio de Agua' },
              {state: 'Heredia', name: 'Heredia' },
              {state: 'Heredia', name: 'Mercedes' },
              {state: 'Heredia', name: 'San Francisco' },
              {state: 'Heredia', name: 'Ulloa' },
              {state: 'Heredia', name: 'Vara Blanca' },
              {state: 'Barva', name: 'Barva' },
              {state: 'Barva', name: 'San Pedro' },
              {state: 'Barva', name: 'San Pablo' },
              {state: 'Barva', name: 'San Roque' },
              {state: 'Barva', name: 'Santa Lucía' },
              {state: 'Barva', name: 'San José de La Montaña' },
              {state: 'Santo Domingo', name: 'Santo Domingo' },
              {state: 'Santo Domingo', name: 'San Vicente' },
              {state: 'Santo Domingo', name: 'San Miguel' },
              {state: 'Santo Domingo', name: 'Paracito' },
              {state: 'Santo Domingo', name: 'Santo Tomás' },
              {state: 'Santo Domingo', name: 'Santa Rosa' },
              {state: 'Santo Domingo', name: 'Tures' },
              {state: 'Santo Domingo', name: 'Pará' },
              {state: 'Santa Bárbara', name: 'Santa Bárbara' },
              {state: 'Santa Bárbara', name: 'San Pedro' },
              {state: 'Santa Bárbara', name: 'San Juan' },
              {state: 'Santa Bárbara', name: 'Jesús' },
              {state: 'Santa Bárbara', name: 'Santo Domingo' },
              {state: 'Santa Bárbara', name: 'Purabá' },
              {state: 'San Rafael', name: 'San Rafael' },
              {state: 'San Rafael', name: 'San Josecito' },
              {state: 'San Rafael', name: 'Santiago' },
              {state: 'San Rafael', name: 'Angeles' },
              {state: 'San Rafael', name: 'Concepción' },
              {state: 'San Isidro', name: 'San Isidro' },
              {state: 'San Isidro', name: 'San José' },
              {state: 'San Isidro', name: 'Concepción' },
              {state: 'San Isidro', name: 'San Francisco' },
              {state: 'Belén', name: 'San Antonio' },
              {state: 'Belén', name: 'Rivera' },
              {state: 'Belén', name: 'Asunción' },
              {state: 'Flores', name: 'San Joaquín' },
              {state: 'Flores', name: 'Barrantes' },
              {state: 'Flores', name: 'Llorente' },
              {state: 'San Pablo', name: 'San Pablo' },
              {state: 'Sarapiquí', name: 'Puerto Viejo' },
              {state: 'Sarapiquí', name: 'La Vírgen' },
              {state: 'Sarapiquí', name: 'Horquetas' },
              {state: 'Sarapiquí', name: 'Llanuras del Gaspar' },
              {state: 'Sarapiquí', name: 'Cureña' },
              {state: 'Liberia', name: 'Liberia' },
              {state: 'Liberia', name: 'Cañas Dulces' },
              {state: 'Liberia', name: 'Mayorga' },
              {state: 'Liberia', name: 'Nacascolo' },
              {state: 'Liberia', name: 'Curubandé' },
              {state: 'Nicoya', name: 'Nicoya' },
              {state: 'Nicoya', name: 'Mansión' },
              {state: 'Nicoya', name: 'San Antonio' },
              {state: 'Nicoya', name: 'Quebrada Honda' },
              {state: 'Nicoya', name: 'Sámara' },
              {state: 'Nicoya', name: 'Nosara' },
              {state: 'Nicoya', name: 'Belén de Nosarita' },
              {state: 'Santa Cruz', name: 'Santa Cruz' },
              {state: 'Santa Cruz', name: 'Bolsón' },
              {state: 'Santa Cruz', name: '27 de Abril' },
              {state: 'Santa Cruz', name: 'Tempate' },
              {state: 'Santa Cruz', name: 'Cartagena' },
              {state: 'Santa Cruz', name: 'Cuajiniquil' },
              {state: 'Santa Cruz', name: 'Diriá' },
              {state: 'Santa Cruz', name: 'Cabo Velas' },
              {state: 'Santa Cruz', name: 'Tamarindo' },
              {state: 'Bagaces', name: 'Bagaces' },
              {state: 'Bagaces', name: 'Fortuna' },
              {state: 'Bagaces', name: 'Mogote' },
              {state: 'Bagaces', name: 'Río Naranjo' },
              {state: 'Carrillo', name: 'Filadelfia' },
              {state: 'Carrillo', name: 'Palmira' },
              {state: 'Carrillo', name: 'Sardinal' },
              {state: 'Carrillo', name: 'Belén' },
              {state: 'Cañas', name: 'Cañas' },
              {state: 'Cañas', name: 'Palmira' },
              {state: 'Cañas', name: 'San Miguel' },
              {state: 'Cañas', name: 'Bebedero' },
              {state: 'Cañas', name: 'Porozal' },
              {state: 'Abangares', name: 'Juntas' },
              {state: 'Abangares', name: 'Sierra' },
              {state: 'Abangares', name: 'San Juan' },
              {state: 'Abangares', name: 'Colorado' },
              {state: 'Tilarán', name: 'Tilarán' },
              {state: 'Tilarán', name: 'Quebrada Grande' },
              {state: 'Tilarán', name: 'Tronadora' },
              {state: 'Tilarán', name: 'Santa Rosa' },
              {state: 'Tilarán', name: 'Líbano' },
              {state: 'Tilarán', name: 'Tierras Morenas' },
              {state: 'Tilarán', name: 'Arenal' },
              {state: 'Nandayure', name: 'Carmona' },
              {state: 'Nandayure', name: 'Santa Rita' },
              {state: 'Nandayure', name: 'Zapotal' },
              {state: 'Nandayure', name: 'San Pablo' },
              {state: 'Nandayure', name: 'Porvenir' },
              {state: 'Nandayure', name: 'Bejuco' },
              {state: 'La Cruz', name: 'La Cruz' },
              {state: 'La Cruz', name: 'Santa Cecilia' },
              {state: 'La Cruz', name: 'Garita' },
              {state: 'La Cruz', name: 'Santa Elena' },
              {state: 'Hojancha', name: 'Hojancha' },
              {state: 'Hojancha', name: 'Monte Romo' },
              {state: 'Hojancha', name: 'Puerto Carrillo' },
              {state: 'Hojancha', name: 'Huacas' },
              {state: 'Puntarenas', name: 'Puntarenas' },
              {state: 'Puntarenas', name: 'Pitahaya' },
              {state: 'Puntarenas', name: 'Chomes' },
              {state: 'Puntarenas', name: 'Lepanto' },
              {state: 'Puntarenas', name: 'Paquera' },
              {state: 'Puntarenas', name: 'Manzanillo' },
              {state: 'Puntarenas', name: 'Guacimal' },
              {state: 'Puntarenas', name: 'Barranca' },
              {state: 'Puntarenas', name: 'Monteverde' },
              {state: 'Puntarenas', name: 'Cóbano' },
              {state: 'Puntarenas', name: 'Chacarita' },
              {state: 'Puntarenas', name: 'Chira' },
              {state: 'Puntarenas', name: 'Acapulco' },
              {state: 'Esparza', name: 'Espíritu Santo' },
              {state: 'Esparza', name: 'San Juan Grande' },
              {state: 'Esparza', name: 'Macacona' },
              {state: 'Esparza', name: 'San Rafael' },
              {state: 'Esparza', name: 'San Jerónimo' },
              {state: 'Buenos Aires', name: 'Buenos Aires' },
              {state: 'Buenos Aires', name: 'Volcán' },
              {state: 'Buenos Aires', name: 'Potrero Grande' },
              {state: 'Buenos Aires', name: 'Boruca' },
              {state: 'Buenos Aires', name: 'Pilas' },
              {state: 'Buenos Aires', name: 'Colinas' },
              {state: 'Buenos Aires', name: 'Chánguena' },
              {state: 'Buenos Aires', name: 'Biolley' },
              {state: 'Montes de Oro', name: 'Miramar' },
              {state: 'Montes de Oro', name: 'Unión' },
              {state: 'Montes de Oro', name: 'San Isidro' },
              {state: 'Osa', name: 'Puerto Cortés' },
              {state: 'Osa', name: 'Palmar' },
              {state: 'Osa', name: 'Sierpe' },
              {state: 'Osa', name: 'Bahía Ballena' },
              {state: 'Osa', name: 'Piedras Blancas' },
              {state: 'Quepos', name: 'Quepos' },
              {state: 'Quepos', name: 'Savegre' },
              {state: 'Quepos', name: 'Naranjito' },
              {state: 'Golfito', name: 'Golfito' },
              {state: 'Golfito', name: 'Puerto Jiménez' },
              {state: 'Golfito', name: 'Guaycará' },
              {state: 'Golfito', name: 'Pavón' },
              {state: 'Coto Brus', name: 'San Vito' },
              {state: 'Coto Brus', name: 'Sabalito' },
              {state: 'Coto Brus', name: 'Agua Buena' },
              {state: 'Coto Brus', name: 'Limoncito' },
              {state: 'Coto Brus', name: 'Pittier' },
              {state: 'Parrita', name: 'Parrita' },
              {state: 'Corredores', name: 'Corredor' },
              {state: 'Corredores', name: 'La Cuesta' },
              {state: 'Corredores', name: 'Canoas' },
              {state: 'Corredores', name: 'Laurel' },
              {state: 'Garabito', name: 'Jacó' },
              {state: 'Garabito', name: 'Tárcoles' },
              {state: 'Limón', name: 'Limón' },
              {state: 'Limón', name: 'Valle La Estrella' },
              {state: 'Limón', name: 'Río Blanco' },
              {state: 'Limón', name: 'Matama' },
              {state: 'Pococí', name: 'Guápiles' },
              {state: 'Pococí', name: 'Jiménez' },
              {state: 'Pococí', name: 'Rita' },
              {state: 'Pococí', name: 'Roxana' },
              {state: 'Pococí', name: 'Cariari' },
              {state: 'Pococí', name: 'Colorado' },
              {state: 'Siquirres', name: 'Siquirres' },
              {state: 'Siquirres', name: 'Pacuarito' },
              {state: 'Siquirres', name: 'Florida' },
              {state: 'Siquirres', name: 'Germania' },
              {state: 'Siquirres', name: 'Cairo' },
              {state: 'Siquirres', name: 'Alegría' },
              {state: 'Talamanca', name: 'Bratsi' },
              {state: 'Talamanca', name: 'Sixaola' },
              {state: 'Talamanca', name: 'Cahuita' },
              {state: 'Matina', name: 'Matina' },
              {state: 'Matina', name: 'Batán' },
              {state: 'Matina', name: 'Carrandí' },
              {state: 'Guácimo', name: 'Guácimo' },
              {state: 'Guácimo', name: 'Mercedes' },
              {state: 'Guácimo', name: 'Pocora' },
              {state: 'Guácimo', name: 'Río Jiménez' },
              {state: 'Guácimo', name: 'Duacarí' }
            ];

            return {
              countries: countries,
              costaRicaProvinces: costaRicaProvinces,
              costaRicaStates: costaRicaStates,
              costaRicaCities: costaRicaCities
            }
        }
})();
